### ISSUE TITLE
Image Preview issue?

### ISSUE THREAD

**Issue by payner35** [orionjs/orion#264]
In the last few days I am having an issue with image preview.. (have tried Bootstrap & materialize)

Some times... very rarely I see the image preview.

![image](https://cloud.githubusercontent.com/assets/939749/9243519/a4b93aa6-41a2-11e5-8454-701d170fbd3c.png)

But most of the time I do not..?

![image](https://cloud.githubusercontent.com/assets/939749/9243542/e526c05e-41a2-11e5-86d7-a6538cddb925.png)

The images are loading in the collection.... they don't seem to be picked up during the render

![image](https://cloud.githubusercontent.com/assets/939749/9243616/ba1c206a-41a3-11e5-84c4-bf40fc848799.png)

Also my text editor froala is not rendering any text... again its available in the collection. but not rendering.

Assuming these two issues are linked. as they both are the results of latest update to packages.

**Comment by payner35** [comment]
getting an error msg now with the upgrade

aldeed:autoform  upgraded from 5.4.0 to 5.4.1 


![image](https://cloud.githubusercontent.com/assets/939749/9276841/6ef8f5ee-42b7-11e5-95f4-2a8a2cb1dd23.png)

**Comment by ffxsam** [comment]
Image thumbnails are no longer showing up unless I hit reload when on the collection editing page.

**Comment by nicolaslopezj** [comment]
Fixed

**Comment by payner35** [comment]
not sure is this related... but I'm still getting the froala error. Text is loading..  maybe a rendering issue as the data loads?

![image](https://cloud.githubusercontent.com/assets/939749/9376436/f8af1d58-471d-11e5-8dec-8b0317352779.png)
